-- MySQL Script generated by MySQL Workbench
-- Tue May  7 18:38:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iot_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iot_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iot_project` DEFAULT CHARACTER SET utf8 ;
USE `iot_project` ;

-- -----------------------------------------------------
-- Table `iot_project`.`dataweatherstation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iot_project`.`dataweatherstation` (
  `code_weatherstation` INT UNSIGNED NOT NULL,
  `datereceive` DATETIME NOT NULL DEFAULT NOW(),
  `stationidentifier` CHAR(12) NOT NULL,
  `winddirection` DECIMAL(5,2) NULL,
  `windspeed` DECIMAL(5,2) NULL,
  `atmosphericpressure` DECIMAL(7,3) NULL,
  `waterevaporation` DECIMAL(5,2) NULL,
  `insolation` TIME NULL,
  `airhumidity` DECIMAL(5,2) NULL,
  `solarradiation` SMALLINT(5) NULL,
  `fluvialprecipitation` DECIMAL(4,1) NULL,
  `temperature` DECIMAL(4,1) NULL,
  `soiltemperature` DECIMAL(4,1) NULL)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `iot_project`.`datasoilsensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iot_project`.`datasoilsensor` (
  `code_soilsensor` INT UNSIGNED NOT NULL,
  `datereceive` DATETIME NOT NULL DEFAULT NOW(),
  `sensoridentifier` CHAR(12) NOT NULL,
  `humidity` DECIMAL(5,2) NULL)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `iot_project`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iot_project`.`user` (
  `code_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `user` VARCHAR(30) NULL,
  `password` CHAR(128) NULL,
  PRIMARY KEY (`code_user`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `iot_project`.`weatherstation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iot_project`.`weatherstation` (
  `code_weatherstation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code_farm` INT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NULL,
  `stationidentifier` CHAR(12) NULL,
  `active` CHAR(1) NULL,
  PRIMARY KEY (`code_weatherstation`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `iot_project`.`soilsensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iot_project`.`soilsensor` (
  `code_soilsensor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code_farm` INT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NULL,
  `sensoridentifier` CHAR(12) NULL,
  `active` CHAR(1) NULL,
  PRIMARY KEY (`code_soilsensor`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `iot_project`.`farm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iot_project`.`farm` (
  `code_farm` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code_user` INT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NULL,
  PRIMARY KEY (`code_farm`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
